name: lumosana

services:
  transaction-debugger:
    build: ../../transaction-debugger
    ports:
      - "8080:8080"
      - "50051:50051"
    env_file:
      - ../../transaction-debugger/.env.docker
    networks:
      - lumosana-network

  envoy:
    image: envoyproxy/envoy:v1.28-latest
    ports:
      - "10000:10000"
      - "9090:9090"
      - "9901:9901"
    volumes:
      - ../envoy/envoy.yaml:/etc/envoy/envoy.yaml
    depends_on:
      - transaction-debugger
    networks:
      - lumosana-network

networks:
  lumosana-network:
    driver: bridge
